---

- hosts: localhost

- hosts: "{{ cluster_name }}_node"

  become: true

  vars:

    kubeadm_packages:
      - docker
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni

  tasks:

    - name: Reset kubeadm
      command: /usr/bin/kubeadm reset
      async: 45
      poll: 0      
      ignore_errors: true

    - name: Remove packages
      yum:
        name: '{{ kubeadm_packages | list }}'
        state: absent
        update_cache: true
      ignore_errors: true

    - name: Add Kubernetes yum repo
      yum_repository:
        name: Kubernetes
#        description: Kubernetes
#        file: kubernetes
#        baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
#        enabled: true
#        gpgcakey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
#        gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg  
#        gpgcheck: true
        state: absent


    - name: yum updates
      yum: name=* state=latest
      remote_user: root

    - name: Remove immutable bit on /var/lib/kubelet
      command: chattr -Ri /var/lib/kubelet/
      ignore_errors: true

    - name: Remove kubernetes directorys
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /etc/kubernetes
        - /var/lib/kubelet
        - /run/kubernetes
      ignore_errors: true

- hosts: "{{ cluster_name }}_master"

  become: true

  vars:

    kubeadm_packages:
      - docker
      - kubelet
      - kubeadm
      - kubectl
      - kubernetes-cni

  tasks:

    - name: Reset kubeadm
      command: /usr/bin/kubeadm reset
      async: 45
      poll: 0
      ignore_errors: true

    - name: Remove packages
      yum:
        name: '{{ kubeadm_packages | list }}'
        state: absent
        update_cache: true
      ignore_errors: true

    - name: Add Kubernetes yum repo
      yum_repository:
        name: Kubernetes
#        description: Kubernetes
#        file: kubernetes
#        baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
#        enabled: true
#        gpgcakey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
#        gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
#        gpgcheck: true
        state: absent


    - name: yum updates
      yum: name=* state=latest
      remote_user: root      
    - name: Remove kubernetes directorys
      file:
        path: '{{ item }}'
        state: absent
      with_items:
        - /etc/kubernetes
        - /var/lib/kubelet
        - /run/kubernetes
        - /var/lib/etcd
      ignore_errors: true        

        
        
