---


- hosts: "{{ cluster_name }}"

  become: true

  roles:

    - role: kubeadm_install_1.6.6
      tags:
        - repo
        - master
        - nodes

- hosts: "{{ cluster_name }}_master"

  become: true

  pre_tasks:

    - name: Read token from file
      include_vars: cfg/{{ cluster_name }}/token.yml

    - name: Read token_ca_cert_hash from file
      include_vars: cfg/{{ cluster_name }}/token_ca_cert_hash.yml

  tasks:

    - set_fact:
        master_ip_address: "{{ master_ip_address_configured }}"
      when: master_ip_address_configured is defined

    - set_fact:
        master_ip_address: "{{ ansible_default_ipv4['address'] }}"
      when: master_ip_address_configured is not defined

    - name: add key to root authorizd_keys file
      shell: cat /home/centos/.ssh/authorized_keys > /root/.ssh/authorized_keys
      when: ansible_user == 'centos'

    - name: Save master_ip_address
      shell: "echo master_ip_address{{ ':' }} {{ master_ip_address }} > cfg/{{ cluster_name }}/master_ip_address.yml"
      delegate_to: 127.0.0.1
      become: false

    - name: kubeadm reset
      command: kubeadm reset

    - name: Initialize master
      command: kubeadm init kubeadm init service-cidr {{ service_cidr }}  apiserver-advertise-address {{ master_ip_address }} kubernetes-version v1.6.6
      register: master_init
      ignore_errors: true
      tags:
        - master
        - init

    - debug:
        var: master_init.stdout_lines

    - set_fact:
        admission_token: "{{ item | regex_replace('^ .*kubeadm join --token ([0-9a-z]{6}.[0-9a-z]{16}) .*$', '\\1') }}"
      when: '"kubeadm join" in item'
      with_items: "{{ master_init.stdout_lines }}"

    - debug:
        var: admission_token

    - name: Copy 10-kubeadm.conf file to nserver
      template: src=master-10-kubeadm.conf-1.6.6.j2 backup=no dest=/etc/systemd/system/kubelet.service.d/10-kubeadm.conf

    - name: Copy /etc/kubernetes/admin.conf on master to cfg/cluster_name/admin.conf
      fetch:
        src: /etc/kubernetes/admin.conf
        dest: cfg/{{ cluster_name }}/admin.conf
        flat: true
      tags:
        - master
        - remote

    - name: Save token id
      shell: "echo admission_token{{ ':' }} {{ admission_token }} > cfg/{{ cluster_name }}/token.yml"
      delegate_to: 127.0.0.1
      become: false

    - set_fact:
        token_ca_cert_hash: "{{ item | regex_replace('^ .*sha256:([0-9a-z]*)$', '\\1') }}"
      when: '"kubeadm join" in item'
      with_items: "{{ master_init.stdout_lines }}"

    - debug:
        var: token_ca_cert_hash

    - name: Save token ca cert hash
      shell: "echo token_ca_cert_hash{{ ':' }} {{ token_ca_cert_hash }} > cfg/{{ cluster_name }}/token_ca_cert_hash.yml"
      delegate_to: 127.0.0.1
      become: false

- hosts: "{{ cluster_name }}_node"

  become: true

  pre_tasks:

    - name: Read token from file
      include_vars: cfg/{{ cluster_name }}/token.yml

    - name: Read token_ca_cert_hash from file
      include_vars: cfg/{{ cluster_name }}/token_ca_cert_hash.yml

    - name: Read master_ip_address from file
      include_vars: cfg/{{ cluster_name }}/master_ip_address.yml

  tasks:

    - debug:
        var: admission_token
      run_once: true

    - debug:
        var: master_ip_address
      run_once: true

    - name: add key to root authorizd_keys file
      shell: cat /home/centos/.ssh/authorized_keys > /root/.ssh/authorized_keys
      when: ansible_user == 'centos'

    - name: Copy 10-kubeadm.conf file to nserver
      template: src=node-10-kubeadm.conf-1.6.6.j2 backup=no dest=/etc/systemd/system/kubelet.service.d/10-kubeadm.conf

    - name: kubeadm reset
      command: kubeadm reset

    - name: Join nodes to cluster
      command: kubeadm join --token {{ admission_token }} {{ master_ip_address }}:6443 --discovery-token-ca-cert-hash sha256:{{ token_ca_cert_hash }}
      register: node_join
      ignore_errors: true
      tags:
        - nodes
        - join

    - debug:
        var: node_join.stdout_lines
