
- hosts: "{{ cluster_name }}_master"
  become: true
  tasks:
    - name: add VSD key to authorized keys file
      authorized_key:
        user: root
        state: present
        key: "{{ lookup('file', '/tmp/vsd.id_rsa.pub') }}"

    - name: "Create user k8s-admin"
      local_action: command python /home/dev/ansible-kubeadm-nuage/files/nuage_create_user.py csproot {{ csproot_passwd }} csp {{ ansible_host }} k8s-admin k8s-admin k8s-admin@nuage.lab
      register: output
      become: false

    - name: Verification Result Failure Status
      fail: msg={{ output.stdout }}
      when: output.stdout != "success"

    - name: Verification Result Success Status
      debug: var=output.stdout

    - name: Create folder /var/k8s/certs
      file:
        path: /var/k8s/certs
        state: directory
        mode: 0755

- hosts: vsd
  become: true
  tasks:
    - name: "Add stat to VSD known_hosts list"
      shell: "ssh-keyscan -t rsa {{ master_ip_address_configured }} | sed -e 's/#.*$//' | sed -e '/^$/d' > /root/.ssh/known_hosts"

- hosts: vsd
  become: true
  tasks:
    - name: "Copying certificates from VSD to k8s Master server"
      shell:  "/opt/vsd/ejbca/deploy/certMgmt.sh -a generate -u k8s-admin -c k8s-admin -o csp -d {{ hostvars[groups['nuage_k8s_master'][0]].inventory_hostname }} -f pem -t server -s root@{{ master_ip_address_configured  }}:/var/k8s/certs"
      become: false
