- hosts: "{{ cluster_name }}_master"

  become: true

  tasks:

    - name: Copy inventory
      template:
        src: "nodes.j2"
        dest: "/root/nuage-k8s-plugin-4.0r8/ansible/nodes"

    - name: Execute playbook
      shell: ./deploy-cluster.sh --tags=nuage
      args:
        chdir: /root/nuage-k8s-plugin-4.0r8/ansible/scripts
      ignore_errors: yes
      become_user: root

    - name: get ansible log lines
      shell: tail -6 /root/nuage-k8s-plugin-4.0r8/ansible/scripts/ansible.log
      register: k8s-plugin

    - name: Show results
      debug:
        var: k8s-plugin.stdout_lines
