---
- name: Install repo epel-release
  shell: yum -y install epel-release

- name: yum updates
  yum: name=* state=latest

- name: Install libselinux as prereq for selinux ansible module
  yum:
    name=libselinux-python
    state=present
  sudo: yes

- name: Disable SELinux at next reboot
  selinux: state=disabled
  sudo: yes

- name: Set SELinux in permissive mode until the machine is rebooted
  shell: setenforce 0
  sudo: yes
  ignore_errors: True

- name: setting /proc/sys/net/bridge/bridge-nf-call-iptables to '1'
  shell: echo '1' > /proc/sys/net/bridge/bridge-nf-call-iptables
  sudo: yes

- name: Flush iptables
  shell: "{{ item }}"
  with_items: 
    - 'iptables -F'
    - 'iptables-save'

- name: Add Kubernetes yum repo
  yum_repository:
    name: Kubernetes
    description: Kubernetes
    file: kubernetes
    baseurl: http://yum.kubernetes.io/repos/kubernetes-el7-x86_64
    enabled: true
    gpgcakey: https://packages.cloud.google.com/yum/doc/yum-key.gpg
    gpgkey: https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg  
    gpgcheck: true
    state: present

- name: Install kubeadm packages
  yum:
    name: '{{ kubeadm_packages | list }}'
    state: latest
    update_cache: true

- name: Enable and start kubeadm services
  service:
    name: '{{ item }}'
    enabled: true
    state: started
  with_items: '{{ kubeadm_services }}'


