FROM centos:7.3.1611

# Install all packages
RUN yum -y install epel-release && yum clean all
RUN curl "https://bootstrap.pypa.io/get-pip.py" -o "get-pip.py"
RUN python get-pip.py
RUN yum -y install ansible && yum clean all
RUN yum -y install curl && yum clean all
RUN yum -y install git && yum clean all

# install sdk from nuage
RUN pip install vspk

# Generate user dev and his files
RUN useradd dev
RUN mkdir -p /home/dev/.ssh
RUN mkdir -p /var/log/ansible
RUN chown -R dev:dev /home/dev
RUN chown -R dev:dev /var/log/ansible
VOLUME /home/dev/.ssh
VOLUME /var/log/ansible
WORKDIR /home/dev
ENV HOME /home/dev
ADD private_key /home/dev/.ssh/id_rsa
RUN chown dev:dev /home/dev/.ssh/id_rsa
RUN chmod 600 /home/dev/.ssh/id_rsa
ADD inventory /home/dev/inventory
ADD setup.sh /home/dev/setup.sh
RUN chmod 755 /home/dev/setup.sh

RUN chown -R dev: /home/dev
USER dev
CMD /home/dev/setup.sh
